#!/bin/bash
rm -rf CMakeCache.txt
rm -rf CMakeFiles

EXTRA_ARGS=$@

TRILINOS_HOME='/scratch/bartv/regression-mrhyde/Trilinos'

INSTALL_DIR='/scratch/bartv/regression-mrhyde/Trilinos-install/DEBUG'

BOOST_DIR='/scratch/bartv/software/boost_1_49_0/include'

NETCDF_INCLUDES='/scratch/bartv/software/netcdf-4.2/install/include'

NETCDF_LIBS='/scratch/bartv/software/netcdf-4.2/install/lib'

/scratch/bartv/software/cmake-3.1.0/install/bin/cmake \
-D CMAKE_BUILD_TYPE:STRING=DEBUG \
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPIEXEC_MAX_NUMPROCS:STRING=8 \
-D CMAKE_CXX_FLAGS:STRING="-g -O0 -ansi -pedantic -ftrapv -Wall -Wno-long-long -Wno-strict-aliasing -DBOOST_NO_HASH" \
-D CMAKE_C_FLAGS:STRING="-g -O0" \
-D CMAKE_Fortran_FLAGS:STRING="-g -O0" \
-D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
-D Trilinos_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Intrepid2_ENABLE_EXAMPLES:STRING=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_IntrepidIntrepid2:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Intrepid_ENABLE_DEBUG_INF_CHECK=OFF \
-D Intrepid2_ENABLE_DEBUG_INF_CHECK:BOOL=OFF \
-D Trilinos_ENABLE_KokkosCore:BOOL=ON \
-D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
-D TPL_ENABLE_Pthread=OFF \
-D Kokkos_ENABLE_Pthread:BOOL=OFF \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_PanzerAdaptersSTK=ON \
-D Trilinos_ENABLE_PanzerDofMgr=ON \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Trilinos_ENABLE_ML:BOOL=ON \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Trilinos_ENABLE_FEI:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_STKClassic:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
-D Trilinos_ENABLE_ROL:BOOL=ON \
-D ROL_ENABLE_EXAMPLES:BOOL=ON \
-D TPL_ENABLE_Matio=OFF \
-D STK_ENABLE_ThreadPool=ON \
-D STK_ENABLE_TESTS:BOOL=OFF \
-D Panzer_ENABLE_TESTS:BOOL=OFF \
-D Panzer_ENABLE_EXAMPLES:BOOL=OFF \
-D Panzer_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Panzer_ENABLE_STKClassic=ON \
-D SEACAS_ENABLE_EXODUS:BOOL=ON \
-D SEACAS_ENABLE_APREPRO:BOOL=OFF \
-D Intrepid_ENABLE_DEBUG_INF_CHECK=OFF \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-D CMAKE_VERBOSE_CONFIGURE:BOOL=ON \
-D CMAKE_SKIP_RULE_DEPENDENCY=ON \
-D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
-D TPL_ENABLE_Boost:BOOL=ON \
-D TPL_Boost_INCLUDE_DIRS:FILEPATH=${BOOST_DIR} \
-D TPL_ENABLE_BoostLib:BOOL=ON \
-D BoostLib_INCLUDE_DIRS:FILEPATH="/scratch/bartv/software/boost_1_49_0/include" \
-D BoostLib_LIBRARY_DIRS:FILEPATH="/scratch/bartv/software/boost_1_49_0/lib" \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D Netcdf_INCLUDE_DIRS:FILEPATH=${NETCDF_INCLUDES} \
-D Netcdf_LIBRARY_DIRS:FILEPATH=${NETCDF_LIBS} \
-D SEACASExodus_ENABLE_MPI:BOOL=OFF \
-D TPL_ENABLE_GLM=OFF \
${EXTRA-ARGS} \
${TRILINOS_HOME}
