mpiexec -n 1 ../../mrhyde inputBlockGmres.yaml >& mrhyde.log
mpiexec -n 1 ../../mrhyde inputBlockCG.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputBiCGStab.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputGCRODR.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputPCPG.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputPseudoBlockCG.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputPseudoBlockGmres.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputPseudoBlockStochasticCG.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputPseudoBlockTFQMR.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputRCG.yaml >> mrhyde.log
mpiexec -n 1 ../../mrhyde inputTFQMR.yaml >> mrhyde.log
