#!/usr/bin/env python3
"""Sweep the decks in solvers.py over a mesh (h) or time-step (cfl) study.

    ./sweep.py {gen|run|report} [h|cfl] [deck ...] [case ...] [all] [krylov]

Arguments come in any order. See README.md.
"""

import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RUNS = HERE / "runs"
EXE = HERE.parents[3] / "mrhyde.exe"

sys.path.insert(0, str(HERE.parents[2] / "scripts" / "data_processing"))
from parse_log import stats  # noqa: E402
from solvers import SOLVERS  # noqa: E402

NP = 4

# (tag, NX, NY, NZ, final time). Every case runs 10 steps, so dt is a tenth of
# the final time and each case costs the same 12 solves.
#
# CFL = dt / h_eff, where 1/h_eff^2 = 1/hx^2 + 1/hy^2 + 1/hz^2 and the wave
# speed is 1 because the deck sets eps = mu = 1. DIRK is implicit so this is
# not a stability limit; it measures how far the stage operator has moved from
# mass-dominated toward curl-curl-dominated. The cfl* tags were named from
# min(h) rather than h_eff, so each understates the real number by 1.22x.
STUDIES = {
    "h": [
        ("N8x8x4", 8, 8, 4, 4.0),
        ("N16x8x4", 16, 8, 4, 4.0),
        ("N24x12x6", 24, 12, 6, 4.0),
        ("N32x16x8", 32, 16, 8, 4.0),
        ("N40x20x10", 40, 20, 10, 4.0),
        ("N48x24x12", 48, 24, 12, 4.0),
        ("N56x28x14", 56, 28, 14, 4.0),
    ],
    "cfl": [
        ("cfl22", 56, 28, 14, 4.0),  # repeats N56x28x14 as a consistency check
        ("cfl8", 56, 28, 14, 1.428571),
        ("cfl4", 56, 28, 14, 0.714286),
        ("cfl2", 56, 28, 14, 0.357143),
        ("cfl1", 56, 28, 14, 0.178571),
        ("cfl0p5", 56, 28, 14, 0.089286),
    ],
}

# Belos solver name.
KRYLOV = {
    "bicgstab": "BiCGStab",
    "gmres": "Block GMRES",
    "gcrodr": "GCRODR",
    "tfqmr": "TFQMR",
}

# Every cfl case is at the finest mesh, so only the h study has cases to trim.
DEFAULT_CASES = {"h": ["N8x8x4", "N16x8x4", "N24x12x6", "N32x16x8"],
                 "cfl": [c[0] for c in STUDIES["cfl"]]}

TEMPLATE = """%YAML 1.1
---
# Generated by sweep.py from {name} in solvers.py. Overwritten by `sweep.py gen`.
# 3D PEC cavity [0,1]x[0,1]x[0,0.5], TM_110, 10 DIRK-1,2 steps.
# mpiexec -n {np} /path/to/mrhyde.exe
ANONYMOUS:
  debug level: 0
  verbosity: 10
  disable timers: false
  print timers: true

  Mesh:
    dimension: 3
    shape: hex
    xmin: 0.0
    xmax: 1.0
    ymin: 0.0
    ymax: 1.0
    zmin: 0.0
    zmax: 0.5
    NX: {nx}
    NY: {ny}
    NZ: {nz}
    blocknames: eblock-0_0_0

  Physics:
    Dirichlet conditions:
      scalar data: false
    eblock-0_0_0:
      modules: maxwell
      assemble boundary terms: false
      Dirichlet conditions:
        Ex:
          all boundaries: "0.0"
        Ey:
          all boundaries: "0.0"
        Ez:
          all boundaries: "0.0"
      Initial conditions:
        "E[x]": "0.0"
        "E[y]": "0.0"
        "E[z]": "sin(pi*x)*sin(pi*y)"
        "B[x]": "0.0"
        "B[y]": "0.0"
        "B[z]": "0.0"

  Discretization:
    eblock-0_0_0:
      order:
        E: 1
        B: 1
      quadrature: 2
      side quadrature: 2

  Functions:
    current x: "0.0"
    current y: "0.0"
    current z: "0.0"
    permittivity: "1.0"
    permeability: "1.0"

  Solver:
    solver: 'transient'
    transient BDF order: 1
    transient Butcher tableau: DIRK-1,2
    number of steps: 10
    final time: {final_time}
    workset size: 100
    assembly partitioning: sequential
    use basis database: false
    use mass database: false
    database TOL: 1.0e-13
    linear TOL: 1.0e-8
    nonlinear TOL: 1.0e-07
    max nonlinear iters: 1
    Belos solver: '{krylov}'
    Belos implicit residual scaling: Norm of Initial Residual
    storage proportion: 1.0
    enable autotune: false
    right preconditioner: true
    use direct solver: false
    use preconditioner: true
    reuse preconditioner: true
    reuse Jacobian: true
    preconditioner reuse type: full
{solver}
  Analysis:
    analysis type: forward

  Postprocess:
    write solution: false
    compute errors: false
    compute integrated quantities: true
    eblock-0_0_0:
      Integrated quantities:
        total_energy:
          integrand: "0.5*(E[x]^2 + E[y]^2 + E[z]^2) + 0.5*(B[x]^2 + B[y]^2 + B[z]^2)"
          location: "volume"
...
"""

def deck_dir(krylov, name, tag):
    return RUNS / krylov / name / tag


def gen(names, cases, krylov):
    for name in names:
        solver, xml = SOLVERS[name]
        for tag, nx, ny, nz, tfinal in cases:
            d = deck_dir(krylov, name, tag)
            d.mkdir(parents=True, exist_ok=True)
            (d / "input.yaml").write_text(TEMPLATE.format(
                name=name, nx=nx, ny=ny, nz=nz, np=NP, solver=solver,
                krylov=KRYLOV[krylov], final_time=tfinal))
            for x in xml:
                shutil.copy2(HERE / "xml" / x, d / x)
    print("wrote %d decks under runs/%s" % (len(names) * len(cases), krylov))


def run(names, cases, krylov):
    if not EXE.is_file():
        sys.exit("no mrhyde at %s" % EXE)
    for name in names:
        for tag, _, _, _, _ in cases:
            d = deck_dir(krylov, name, tag)
            if not (d / "input.yaml").exists():
                sys.exit("%s/%s/%s not generated; run `sweep.py gen`"
                         % (krylov, name, tag))
            with open(d / "mrhyde.log", "w") as f:
                rc = subprocess.call(["mpiexec", "-n", str(NP), str(EXE)],
                                     cwd=d, stdout=f, stderr=subprocess.STDOUT)
            print("  %-26s %-10s %s%s" % (name, tag, summarize(d / "mrhyde.log"),
                                          "" if rc == 0 else " (exit %d)" % rc),
                  flush=True)


def summarize(log):
    s = stats(log)
    if not s:
        return "no solves"
    # A diverging solve reports its last iteration, not a convergence count,
    # so report drops these to a dash rather than averaging them in.
    if s["unconv"]:
        return "%d of %d solves did not converge" % (s["unconv"], s["solves"])
    return "%d solves, mean %.2f, max %d" % (s["solves"], s["mean"], s["max"])


def table(title, names, tags, cell):
    vals = {(n, t): cell(n, t) for n in names for t in tags}
    w = max([len(n) for n in names] + [len("deck")]) + 2
    c = max([len(t) for t in tags] + [len(v) for v in vals.values()]) + 1
    print("\n%s\n" % title)
    print("%-*s" % (w, "deck") + "".join("%*s" % (c, t) for t in tags))
    print("-" * (w + c * len(tags)))
    for name in names:
        print("%-*s" % (w, name) + "".join("%*s" % (c, vals[name, t]) for t in tags))


def report(names, cases, krylov):
    tags = [c[0] for c in cases]
    data = {}
    for name in names:
        for tag in tags:
            s = stats(deck_dir(krylov, name, tag) / "mrhyde.log")
            if s and not s["unconv"]:
                data[name, tag] = s
    if not data:
        sys.exit("no results under runs/%s -- try `sweep.py run`" % krylov)

    tags = [t for t in tags if any((n, t) in data for n in names)]
    head = "%s, " + KRYLOV[krylov] + ", %d ranks" % NP

    def cell(key, fmt):
        return lambda n, t: fmt % data[n, t][key] if (n, t) in data else "-"

    table(head % "Belos iterations per solve, mean", names, tags,
          cell("mean", "%.1f"))
    table(head % "Forward solve wall time, seconds", names, tags,
          cell("fwd", "%.2f"))
    if any((n, t) not in data for n in names for t in tags):
        print("\nDash: not run, crashed, or out of iterations. See "
              "runs/%s/<deck>/<case>/mrhyde.log." % krylov)


COMMANDS = {"gen": gen, "run": run, "report": report}


def parse_args(argv):
    """-> (command, deck names, cases, krylov key)."""
    if not argv or argv[0] not in COMMANDS:
        sys.exit(__doc__)
    cmd, rest = argv[0], argv[1:]

    study = "cfl" if "cfl" in rest else "h"
    cases = STUDIES[study]
    tags = [c[0] for c in cases]

    unknown = [a for a in rest
               if a not in set(SOLVERS) | set(tags) | set(KRYLOV) | {"all", "h", "cfl"}]
    if unknown:
        sys.exit("not a deck, case, study, or Krylov solver: %s" % ", ".join(unknown))
    krylov = [a for a in rest if a in KRYLOV]
    if len(krylov) > 1:
        sys.exit("one Krylov solver at a time")

    named = [a for a in rest if a in tags]
    if "all" in rest:
        picked = tags
    elif named:
        picked = named
    elif cmd == "gen":
        picked = tags  # gen writes every case so xml/ edits leave no stale copies
    else:
        picked = DEFAULT_CASES[study]

    return (cmd,
            [a for a in rest if a in SOLVERS] or list(SOLVERS),
            [c for c in cases if c[0] in picked],
            krylov[0] if krylov else "bicgstab")


def main():
    cmd, names, cases, krylov = parse_args(sys.argv[1:])
    COMMANDS[cmd](names, cases, krylov)


if __name__ == "__main__":
    main()
