% Script to load data generated by MrHyDE

N = 1000;
M = 61^2;

sol = zeros(M,N);
sol_dp1 = sol;
sol_dp2 = sol;
sol_dp3 = sol;
sol_dp4 = sol;
sol_dp5 = sol;
sol_dp6 = sol;
sol_dp7 = sol;
sol_dp8 = sol;
sol_dp9 = sol;

delta = 1.0e-5;

for k=1:N

    k
    index = num2str(k-1);
    val = load(strcat(['solutions/solution.' index '.0.dat']));
    dp1 = load(strcat(['dp1/solution.' index '.0.dat']));
    dp2 = load(strcat(['dp2/solution.' index '.0.dat']));
    dp3 = load(strcat(['dp3/solution.' index '.0.dat']));
    dp4 = load(strcat(['dp4/solution.' index '.0.dat']));
    dp5 = load(strcat(['dp5/solution.' index '.0.dat']));
    dp6 = load(strcat(['dp6/solution.' index '.0.dat']));
    dp7 = load(strcat(['dp7/solution.' index '.0.dat']));
    dp8 = load(strcat(['dp8/solution.' index '.0.dat']));
    dp9 = load(strcat(['dp9/solution.' index '.0.dat']));

    sol(:,k) = val;
    sol_dp1(:,k) = (dp1-val)/delta;
    sol_dp2(:,k) = (dp2-val)/delta;
    sol_dp3(:,k) = (dp3-val)/delta;
    sol_dp4(:,k) = (dp4-val)/delta;
    sol_dp5(:,k) = (dp5-val)/delta;
    sol_dp6(:,k) = (dp6-val)/delta;
    sol_dp7(:,k) = (dp7-val)/delta;
    sol_dp8(:,k) = (dp8-val)/delta;
    sol_dp9(:,k) = (dp9-val)/delta;
end

dlmwrite('combined_sol.dat',sol,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp1.dat',sol_dp1,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp2.dat',sol_dp2,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp3.dat',sol_dp3,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp4.dat',sol_dp4,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp5.dat',sol_dp5,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp6.dat',sol_dp6,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp7.dat',sol_dp7,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp8.dat',sol_dp8,'delimiter','\t','precision','%1.12f')
dlmwrite('combined_dp9.dat',sol_dp9,'delimiter','\t','precision','%1.12f')
