#!/bin/bash
rm -rf CMakeCache.txt
rm -rf CMakeFiles

EXTRA_ARGS=$@

# Machine name: s1060545
# Machine type: mac laptop OS Catalina
# Build type: serial

# Modules installed using Homebrew
#  1) zlib-1.2.11                                     6) hdf5-mpi-1.12.0_1 
#  2) pnetcdf-1.12.1_1                                7) libx11-1.6.9  
#  3) gcc-10.2.0                                      8) netcdf-4.7.4_1 
#  4) open-mpi-4.0.5                                  9) cmake-3.18.4 
#  5) boost-1.73.0                                   10) ninja-1.10.1 

# Notes
#  1) Installing pnetcdf also installed gcc-10.20 and open-mpi-4.0.5.
#  2) Installng pnetcdf also installed hdf5.  This did not appear to build properly, so I then installed netcdf and hdf5-mpi.  I believe only netcdf and hdf5-mpi are actually used.
#  3) This build uses gcc-10.2.0 instead of clang.  To make sure clang is not used I set the following in ~/.bash_profile:
#       alias gcc=gcc-10
#       alias g++=g++-10
#       alias c++=g++
#       alias gfortran=gfortran-10
#       export OMPI_CC=gcc-10
#       export OMPI_CXX=g++-10
#       export OMPI_FC=gfortran-10
 
TRILINOS_HOME='/Users/tmwilde/Software/Trilinos'

INSTALL_DIR='/Users/tmwilde/Software/Trilinos/trilinos-gcc-debug'

cmake \
-GNinja \
-D CMAKE_BUILD_TYPE:STRING=DEBUG \
-D TPL_ENABLE_MPI:BOOL=ON \
-D CMAKE_CXX_FLAGS:STRING="-O3 -ansi -pedantic -ftrapv -Wall -Wno-long-long -Wno-strict-aliasing -DBOOST_NO_HASH" \
-D CMAKE_C_FLAGS:STRING="-O3" \
-D CMAKE_Fortran_FLAGS:STRING="-O3" \
-D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
-D Trilinos_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_ROL:BOOL=ON \
-D Trilinos_ENABLE_PanzerCore=ON \
-D Trilinos_ENABLE_PanzerDofMgr=ON \
-D Trilinos_ENABLE_PanzerMiniEM=OFF \
-D Trilinos_ENABLE_PanzerAdaptersSTK=ON \
-D Trilinos_ENABLE_Intrepid2:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_MueLu:BOOL=ON \
-D Trilinos_ENABLE_Percept:BOOL=OFF \
-D PanzerAdaptersSTK_ENABLE_EXAMPLES=OFF \
-D PanzerAdaptersSTK_ENABLE_TESTS=OFF \
-D TPL_ENABLE_Matio=OFF \
-D STK_ENABLE_TESTS:BOOL=OFF \
-D Panzer_ENABLE_TESTS:BOOL=OFF \
-D Panzer_ENABLE_EXAMPLES:BOOL=OFF \
-D Panzer_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D PANZER_HAVE_PERCEPT:BOOL=OFF \
-D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
-D TPL_ENABLE_Boost:BOOL=ON \
-D TPL_ENABLE_BoostLib:BOOL=ON \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D TPL_ENABLE_HDF5=ON \
-D SEACASExodus_ENABLE_MPI:BOOL=OFF \
-D TPL_ENABLE_GLM=OFF \
-D Kokkos_ENABLE_SERIAL=ON \
-D Kokkos_ENABLE_DEBUG=ON \
-D Intrepid2_ENABLE_DEBUG=ON \
${EXTRA-ARGS} \
${TRILINOS_HOME}

