#!/bin/bash
rm -rf CMakeCache.txt
rm -rf CMakeFiles

EXTRA_ARGS=$@

TRILINOS_HOME='/ascldap/users/dtseidl/src/trilinos'

INSTALL_DIR='/ascldap/users/dtseidl/local/trilinos-opt'

BOOST_INCLUDE_DIR='/ascldap/users/dtseidl/include'

BOOST_LIB_DIR='/ascldap/users/dtseidl/lib'

NETCDF_INCLUDE_DIR='/ascldap/users/dtseidl/local/include'

NETCDF_LIB_DIR='/ascldap/users/dtseidl/local/lib'

MATIO_INCLUDE_DIR='/ascldap/users/dtseidl/local/include'

MATIO_LIB_DIR='/ascldap/users/dtseidl/local/lib'

/ascldap/users/dtseidl/local/bin/cmake \
-D CMAKE_BUILD_TYPE:STRING=NONE \
-D TPL_ENABLE_MPI:BOOL=ON \
-D CMAKE_CXX_FLAGS:STRING="-O3 -ansi -pedantic -ftrapv -Wall -Wno-long-long -Wno-strict-aliasing -DBOOST_NO_HASH" \
-D CMAKE_C_FLAGS:STRING="-O3" \
-D CMAKE_Fortran_FLAGS:STRING="-O3" \
-D Trilinos_ENABLE_CHECKED_STL:BOOL=OFF \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
-D Trilinos_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_ROL:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_Panzer:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Trilinos_ENABLE_ML:BOOL=ON \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Trilinos_ENABLE_FEI:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_STKClassic:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D TPL_ENABLE_Matio=OFF \
-D STK_ENABLE_TESTS:BOOL=OFF \
-D Panzer_ENABLE_TESTS:BOOL=OFF \
-D Panzer_ENABLE_EXAMPLES:BOOL=OFF \
-D Panzer_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-D CMAKE_SKIP_RULE_DEPENDENCY=ON \
-D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
-D TPL_ENABLE_Boost:BOOL=ON \
-D TPL_Boost_INCLUDE_DIRS:FILEPATH=${BOOST_INCLUDE_DIR} \
-D TPL_ENABLE_BoostLib:BOOL=ON \
-D BoostLib_INCLUDE_DIRS:FILEPATH=${BOOST_INCLUDE_DIR} \
-D BoostLib_LIBRARY_DIRS:FILEPATH=${BOOST_LIB_DIR} \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D Netcdf_LIBRARY_DIRS:FILEPATH=${NETCDF_LIB_DIR} \
-D SEACASExodus_ENABLE_MPI:BOOL=OFF \
-D TPL_ENABLE_GLM=OFF \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D TPL_Netcdf_INCLUDE_DIRS:PATH=${NETCDF_INCLUDE_DIR} \
-D TPL_Netcdf_Enables_Netcdf4:BOOL=ON \
-D TPL_Netcdf_Enables_PNetcdf:BOOL=ON \
-D TPL_ENABLE_Matio:BOOL=ON \
-D Matio_LIBRARY_DIRS:PATH=${MATIO_LIB_DIR} \
-D TPL_Matio_INCLUDE_DIRS:PATH=${MATIO_INCLUDE_DIR} \
-D TPL_X11_INCLUDE_DIRS:PATH=/usr/include/X11 \
-D Trilinos_EXTRA_LINK_FLAGS:STRING="-L/ascldap/users/dtseidl/local/lib -lpnetcdf -lhdf5_hl -lhdf5 -lz" \
${EXTRA-ARGS} \
${TRILINOS_HOME}
