#!/bin/bash
EXTRA_ARGS=$@

rm CMakeCache.txt

TRILINOS_HOME="/Users/${USER}/src/trilinos"

TRILINOS_INSTALL="/Users/${USER}/local/trilinos-opt"

CODE_HOME="/Users/${USER}/src/milo-3d"

CODE_INSTALL="/Users/${USER}/local/milo-opt"

cmake \
-D Trilinos_SRC_DIR=${TRILINOS_HOME} \
-D Trilinos_INSTALL_DIR=${TRILINOS_INSTALL} \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-D CMAKE_INSTALL_PREFIX:PATH=${CODE_INSTALL} \
${EXTRA-ARGS} \
${CODE_HOME}
